name: Build PyInstaller

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            extension: exe
          - os: macos-latest
            extension: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --windowed --additional-hooks-dir=. --icon=assets/app_icon.ico -F file_cleaner_gui.py --name "File_Cleaner"
        shell: bash

      - name: Zip .app file (macOS only)
        if: matrix.os == 'macos-latest'
        run: |
          cd dist
          zip -r File_Cleaner.zip . -i File_Cleaner.app

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-files
          path: |
            dist/File_Cleaner.${{ matrix.extension }}
            dist/File_Cleaner.zip
