name: Build PyInstaller

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            extension: exe
          - os: macos-latest
            extension: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --windowed --additional-hooks-dir=. --icon=assets/app_icon.ico -F file_cleaner_gui.py
        shell: bash

      - name: Rename output file
        run: |
          mv dist/file_cleaner_gui dist/File_Cleaner.${{ matrix.extension }}

      - name: Zip .app file (macOS only)
        if: matrix.os == 'macos-latest'
        run: |
          cd dist
          zip -r File_Cleaner.zip . -i File_Cleaner.app || echo "No .app file found, skipping zip"

      - name: Upload .exe artifact (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: File_Cleaner.exe
          path: dist/File_Cleaner_Windows.exe
          if-no-files-found: warn

      - name: Upload .zip artifact (macOS only)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: File_Cleaner_macOS.zip
          path: dist/File_Cleaner.zip
          if-no-files-found: warn
